name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
    - name: Test all
      run: |
        python backend/tests.py
        npm run test
#     - name: Code Coverage
#       run: |
#         python -m pip install coverage
#         pip install coverage-badge
#         python -m coverage run -m backend.app
#         python -m coverage report 
#         # coverage-badge -o coverage.svg	        
#         # percent=$(tail -1 coverage_report.txt | awk '{print $(NF)}')
#         # echo "Code coverage = $percent"
    - name: CodeCov
      uses: codecov/codecov-action@v3
      with:
        token:  a891e16e-8e19-4db2-8b59-04ba1664be2c


