name: sphinx-autogenerator

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build documentation and commit
      run: |
          git pull origin master
          cd docs/
          sudo apt-get install python3-sphinx
          sudo rm backend.rst
          sudo rm modules.rst
          sphinx-apidoc -o . ../backend/
          make html
          cd ..
          git config --global user.name "gowtham-sathyan"
          git config --global user.email "gowthamsathyan@gmail.com"
          git add .
          git commit -m "Updated documentation" -a || true
          git push
    # ===============================
