name: sphinx-autogenerator

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - uses: actions/checkout@v2
    - name: Build documentation and commit
      run: |
          git checkout -b doc_temp
          cd docs/
          sudo apt-get install python3-sphinx
          sudo rm backend.rst
          sudo rm modules.rst
          sphinx-apidoc -o . ../backend/
          make html
          cd ..
          git config --global user.name "Parth-25m"
          git config --global user.email "partha.25m@gmail.com"
          git add .
          git commit -m "Updated documentation" -a || true
          git push origin doc_temp
    # ===============================
